# Tabela True/False
a = (2 > 3) and (5 != 0)   
b = (4 < 10) and (3 == 3)
c = (7 >= 7) or (2 > 5)
d = not (3 < 1) and (6 == 6)
e = (8 != 8) or (10 > 2)
f = not (5 > 3 and 2 < 1)
g = (9 > 5) and not (4 == 4)
h = (6 < 2) or (3 != 3) or (1 == 1)
i = not (2 > 1) or (5 >= 5 and 3 < 4)
j = (10 != 10) and (not (2 < 3) or (8 > 1))
k = (10 > 5) and ("a" == "a")
l = ("python" != "Python") or (3 * 2 == 6)
m = (4 + 1 == 6) or ("chat" == "chat")

print("Resultado de a:", a)
print("Resultado de b:", b)
print("Resultado de c:", c)
print("Resultado de d:", d)
print("Resultado de e:", e)
print("Resultado de f:", f)
print("Resultado de g:", g)
print("Resultado de h:", h)
print("Resultado de i:", i)
print("Resultado de j:", j)
print("Resultado de k:", k)
print("Resultado de l:", l)
print("Resultado de m:", m)


